#!/usr/bin/env bash

app_name=$(basename "$0")

conf_dir="$HOME/.config/$app_name"
conf_file="$conf_dir/$app_name.conf"

function load_config() {
  # Return __NONE__ if the value is not defined in the config file
  (grep -E "^$1=" -m 1 "$conf_file" 2>/dev/null || echo "=__NONE__") | head -n 1 | cut -d '=' -f 2-
}

function parse_comma_list() {
  local tmp="$IFS"
  IFS=","
  local list=($1)
  IFS="$tmp"
  echo "${list[*]}"
}

if ! command -v trans &>/dev/null; then
  echo "Please install: https://www.soimort.org/translate-shell/"
  exit 1
fi

# Retrieve list of valid language codes
valid_codes=$(trans -list-codes)

# Convert code list to associative array
declare -A "valid_codes=($(echo ${valid_codes[@]} | sed 's/[^ ]*/[&]=&/g'))"

# For lanaguages that have several variants, also index the generic language code
for code in "${!valid_codes[@]}"; do
  stub=${code%-*}
  valid_codes[$stub]=$stub
done

function is_valid_lang() {
  [[ -v valid_codes[$1] ]]
}

# Escape sequences for highlighting
_YELLOW=$'\001\e[33m\002'
_GREEN=$'\001\e[32m\002'
_RESET=$'\001\e[m\002'

# Source language
from=en

# Use an associative array to make it easy to add/remove elements
declare -A langs

function add_langs() {
  local list=($(parse_comma_list $1))

  for item in "${list[@]}"; do
    if is_valid_lang $item; then
      if [[ ! -v langs[$item] ]]; then
        [[ -n $2 ]] && echo "Adding language: $item"

        langs[$item]=$item
      fi
    else
      echo "Invalid language code: $item"
    fi
  done
}

# Save source and target languages to configuration file
function save_config() {
  # Create the config directory if it doesn't exist
  mkdir -p "$conf_dir"

  local tmp="$IFS"
  IFS=","
  echo -e "from=$from\nto=${langs[*]}" > "$conf_file"
  IFS="$tmp"
}

# Load source and target languages from configuration file
function load_langs() {
  # If configuration file doesn't exist, don't do anything
  [ -f "$conf_file" ] || return 1

  local val=$(load_config from)

  if [[ $val != __NONE__ ]]; then
    if is_valid_lang "$val"; then
      from="$val"
    else
      echo "Invalid source language in configuration file: $val"
    fi
  fi

  val=$(load_config to)

  [[ $val == __NONE__ ]] && return 1

  # Set target languages based on configuration file
  add_langs "$val"
}

load_langs || langs=([el]=el [hu]=hu [sv]=sv)

echo "Type /? for help"
echo

while
  # Prompt content
  prompt="$from -> ${langs[*]:-[no languages]}> "

  # Read input with prompt
  read -erp "$_GREEN$prompt$_RESET" input
do
  echo

  if [ -z "$input" ]; then
    echo 'Type /? for help'
  elif [[ ${input:0:1} == '/' ]]; then
    input=( $input )

    # Isolate the command
    cmd=${input[0]}

    # Remove the command itself from the input (leave just the arguments)
    input=${input[@]:1}

    case $cmd in
      /[ac] )
        # Clear the language list if /c is the command
        if [[ "$cmd" == /c ]]; then
          langs=()
        fi

        add_langs "${input[1]}" 1

        save_config

        # If language list is now empty, suggest setting a language
        if [ ${#langs[@]} -eq 0 ]; then
          echo 'Type /a [lang] to set a language'
        fi
        ;;

      /d )
        list=($(parse_comma_list ${input[1]}))

        for item in "${list[@]}"; do
          if [[ -v langs[$item] ]]; then
            echo "Removing language: $item"

            unset langs[$item]
          fi
        done

        save_config
        ;;

      /f )
        if is_valid_lang ${input[1]}; then
          echo "Setting source language: ${input[1]}"
          from=${input[1]}

          save_config
        else
          echo "Invalid source language: ${input[1]}"
        fi
        ;;

      /l )
        echo 'Supported languages:'
        echo

        # Print table of supported languages
        trans -T
        ;;

      '/?' )
        echo '/c {fr,de,bg,...} - clear languages (set them from scratch)'
        echo '/a fr{,de,bg,...} - add language(s)'
        echo '/d fr{,de,bg,...} - remove language(s)'
        echo '/f pl             - set source language'
        echo '/l                - show supported languages'
        echo '/?                - print help'
        echo '/q                - quit'
        ;;

      /q )
        exit
        ;;

      * )
        echo "Unknown command: $cmd"
        ;;
    esac
  else
    if [ ${#langs[@]} -eq 0 ]; then
      echo 'Type /? for help'
    else
      # Trap ^C signal, so that it cancels the translation queries but doesn't quit the program
      trap 'echo " - Cancelled query"' INT

      # Launch asynchronous translation requests for all target languages
      for lang in ${langs[*]}; do
        echo -e "$_YELLOW$lang:$_RESET $(trans -no-warn -b -s "$from" -t "$lang" "$input")" &
      done

      # Wait for all asynchronous requests to complete
      wait

      # Clear ^C trap
      trap - INT
    fi
  fi

  echo
done
